### ISSUE TITLE
Total Crash of Windows

### ISSUE THREAD

**Issue by TimBakkerVBH** [dapplo/Dapplo.Confluence#53] opened 2021-10-27 13:14 UTC
Hi,

I tried the NuGET package but my whole laptop just crash hard with a blue screen of death and rebooted itself.
I'm using a project with .Net Framework 4.7.2 with an empty winforms project and just the following code:

            var client = Dapplo.Confluence.ConfluenceClient.Create(new Uri("xxxx"));
            return await client.IsCloudServer();

I never seen this before with Visual Studio. Using version 16.11.3 (VS2019)

Do you have any idea where this is coming from?

Tim

**Comment by Lakritzator** [comment] 2021-11-02 10:15
@TimBakkerVBH I would love to see you push a small example solution to a repository, so I can see if this happens on my side too or look at what code you are using exactly. Can you do this?

**Comment by TimBakkerVBH** [comment] 2021-11-02 10:17
Yes i will start working on my confluence implementation shortly and perform some tests with another pc. Sorry for the delay, a lot to be done in short amount of time.

**Comment by Lakritzator** [comment] 2021-11-02 10:20
No problem, I just want to make sure there is nothing on my side.

Although I cannot think of any way this is caused by my nuget package, I have seen more weird stuff during my life, so... rather be on the safe side 😉

**Comment by TimBakkerVBH** [comment] 2021-11-17 21:29
Okay i finally found some time to investigate and after some more BSODs i installed fresh install of Windows and VS2022. Now the i can run code without BSOD every time. I guess something was corrupt with a driver.

Is there any documentation is can use to get started? I found only the readme here.

**Comment by Lakritzator** [comment] 2021-11-22 15:04
I think there could be a lot more documentation, but as I do this all for free, one cannot expect everything is there.

I hope you already know your way around Confluence a bit, otherwise it's impossible to find what you need.
I would advice you to first write down what you want to do.
After that, take a look at the test cases, and see if you can find examples there.

If not, let me know and I will see what I can do.

**Comment by TimBakkerVBH** [comment] 2021-11-23 09:30
I understand completely and after some fiddeling around i found everything i needed.
Thank you very much for the nice package of tools and it saved me a ton of time (except for the windows parts, but that's fixed now hopefully!)

Now starting with Jira!

**Comment by Lakritzator** [comment] 2022-01-08 16:16
Closing this issue, as I guess there is nothing left to do.

I hope you also find your way around the Jira project... it's very similar!

**Closed by Lakritzator** 2022-01-08 16:16 UTC
Labels: Awaiting feedback
